name: "bundle exec"

on:
  push:
    branch:
      - master
    paths:
      - 'lib/**'
      - 'spec/**'
      - '.github/workflows/bundle.yaml'
  schedule:
    - cron: '0 11 */4 * *'

jobs:
  BundleInstall:
    runs-on: ubuntu-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: false
          ruby-version: 3.1
      - name: bundle install gems
        run: |
          mkdir sample 
          cd sample
          bundle init
          ## add dependency
          DEP_URL=https://github.com/takuya/ruby-google-xoauth2.git
          echo gem "'takuya-xoauth2', git: '$DEP_URL'" >> Gemfile
          ## add this repository
          REPO_URL=https://github.com/takuya/ruby-gmail-forwarder.git
          echo "gem 'takuya-gmail-forwarder', git: '$REPO_URL'" >> Gemfile
          ## sample file
          cat <<EOS > sample.rb
          require 'takuya/gmail-forwarder'
          class MyProxy < Takuya::GMailForwarderServer
          end
          EOS
          ## run sample
          bundle exec ruby sample.rb


